#! /usr/bin/python2
import sys

try:
    from nittygriddy import parser
except ImportError, e:
    print "There was an import error! Was ROOT `source`ed properly?"
    print e
    quit()

parser = parser.create_parser()
args = parser.parse_args()

try:
    args.op(args)
except KeyboardInterrupt:
    sys.exit(1)
except Exception as e:
    if args.verbose:
        # re-raise with the full traceback
        t, v, tb = sys.exc_info()
        raise t, v, tb
    else:
        sys.exit("{0}: {1}".format(e.__class__.__name__, e))
